### ISSUE TITLE
How to create a Distribution PKG for El Capitan 10.11 Installer

### ISSUE THREAD

**Issue by sveneuve** [munki/createOSXinstallPkg#11]
I tried many times to add a Package "DisableSetupAssistent.pkg" to the Installer, but it dosen´t work. The Script in the PKG won´t execute at the Installation, the manual Install of the additional PKG work fine. I have read the Information for Yosemite, that only Distribution Packages will be supported. Mens this the same for El Capitan? I think yes, and i created a Distribution Package with the App "Packages", but it won´t work. A convert from a Jamf Composer FlatPackage was failed. How did you create those Packages to include this?

**Comment by gregneagle** [comment]
What does "it doesn't work" mean? What errors do you see? What failures do you observe?

I'm guessing the problem is with the _script_ in your package. There really is no need for scripts in this sort of package, and scripts can often be the source of failure when you make assumptions about the install environment.

"I have read the Information for Yosemite, that only Distribution Packages will be supported. Mens this the same for El Capitan?"  Yes.

Here's one that works for me: https://dl.dropboxusercontent.com/u/8119814/SuppressSetupAssistant.pkg

**Comment by gregneagle** [comment]
Here's a tool for creating packages in a sane, repeatable manner: https://github.com/munki/munki-pkg
It even comes with a sample project to suppress the SetupAssistant: https://github.com/munki/munki-pkg/tree/master/SuppressSetupAssistant

**Comment by sveneuve** [comment]
I see no Errors, the Package will be not execute after the OS X Upgrade.

I think the Script is not the Problem. It works, when i execute it manually or in a Package via munki.

I will try your Package for the Setup Assistant.

Thaks a lot!

Sven

**Comment by gregneagle** [comment]
"I think the Script is not the Problem. It works, when i execute it manually or in a Package via munki."

I think the script _is_ the problem, but without seeing it, I can only guess. Your observations are consistent with a script that attempts to modify files -- it's probably trying to modify files on the current startup disk. This will work when you are running the package manually or via Munki, because the target disk for the installation _is_ the startup disk.

But when installing to a volume other than the current startup volume, your script is attempting to change the wrong files and the wrong paths -- during an OS X install, the install target volume is _not_ the current startup disk.

You'd see the exact same issue if you attempted to install your package in an AutoDMG workflow, or when booted into a Netboot/Netinstall/NetRestore/DeployStudio workflow, or any other workflow where the target volume is not the startup disk.

**Comment by sveneuve** [comment]
Is there a possible way to prevent new and also existing Users from the „sign in with your Apple ID“ Massage after Upgrading from 10.10 to 10.11 via munki?

The Clients were enrolled with OS 10.10 via DeployStudio with a AutoDMG Image and the "sign in“ Massage was disable via Script in the User Templates.

Me intesion was to execute this Script via pkg with the the 10.11 Upgrage Installer.
I will try this with the recommended Tools from you.
But how can i catch the existing Users?

**Comment by gregneagle** [comment]
That must be handled either via a configuration profile or a script that runs at login, as that's a user-level assistant and preference, and not part of the initial computer setup assistant.

I think Rich Trouton has written about this on his blog at https://derflounder.wordpress.com.

**Comment by rtrouton** [comment]
Profile method for suppressing the iCloud pop-up message: [https://derflounder.wordpress.com/2016/01/28/suppressing-the-icloud-and-diagnostics-pop-up-windows-on-el-capitan-using-profiles/](https://derflounder.wordpress.com/2016/01/28/suppressing-the-icloud-and-diagnostics-pop-up-windows-on-el-capitan-using-profiles/)

Script method for suppressing the iCloud pop-up message: [https://github.com/rtrouton/rtrouton_scripts/tree/master/rtrouton_scripts/disable_apple_icloud_and_diagnostic_pop_ups](https://github.com/rtrouton/rtrouton_scripts/tree/master/rtrouton_scripts/disable_apple_icloud_and_diagnostic_pop_ups)
